In [10]:
#Задание 1
'''Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).'''
import numpy as np
n = input('Введите число:')
a = np.arange(0, int(n))
b = a [::-1]
print (b)

Введите число:7
[6 5 4 3 2 1 0]


In [18]:
#Задание 2
'''Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.'''
k = input('Введите число:')
c = np.arange(0, int(k))
d = c [::-1]
m= np.diag(d)
print(m)
np.trace(m)

Введите число:9
[[8 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]


36

In [22]:
#Задание 3
'''Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3'''
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4 ] ] ) # коэффициенты при переменных в левой части уравнения
b = np.array( [4, 12, -3] ) # значения в правой части уравнения
from numpy import linalg
print(linalg.solve(a, b)) # решение
np.allclose( np.dot(a, linalg.solve(a, b)), b ) # проверка верности

[ 0.46666667  3.84444444 -5.55555556]


True

In [5]:
#Задание 4
'''Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
Остальные столбцы - количество покупок категорий товаров этим пользователем. На сайт заходит очередной посетитель.
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats'''
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


In [6]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """ 
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [19]:
max_=0
for i, row in enumerate(users_stats,1):
    k = cosine(row, next_user_stats)
    if k > max_:
        max_ = k
        max_i = i

#res = max([cosine(row, next_user_stats) for row users_stats]) 

print(f'самый  похожий пользователь с User ID {max_i}')

самый  похожий пользователь с User ID 8
